# Generated by Django 3.0.4 on 2020-03-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=70, null=True)),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
                ('assign_to', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_budget', models.IntegerField(blank=True, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='media/')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('values', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('skype_id', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('values_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reject_reason', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=20, null=True)),
                ('rejected_date', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts_Reject', to='accounts.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=180)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts_Comments', to='accounts.Accounts')),
            ],
        ),
    ]
