# Generated by Django 2.2.9 on 2020-02-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Source', models.CharField(max_length=300)),
                ('Url', models.CharField(max_length=300)),
                ('Domain', models.CharField(max_length=300)),
                ('Tags', models.CharField(max_length=3000)),
                ('Technology', models.CharField(max_length=300)),
                ('AssignTo', models.CharField(max_length=300)),
                ('EstimatedBudget', models.IntegerField()),
                ('ReferredBy', models.CharField(max_length=300)),
                ('Attachment', models.FileField(upload_to='')),
                ('FullName', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('Company', models.CharField(max_length=300)),
                ('Designation', models.CharField(max_length=300)),
                ('SkypeID', models.CharField(max_length=300)),
                ('StreetAddress', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
                ('Phone', models.CharField(max_length=300)),
            ],
        ),
    ]
