# Generated by Django 3.0.3 on 2020-04-03 08:33

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='values',
            new_name='secondary_email1',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='values_phone',
        ),
        migrations.AddField(
            model_name='accounts',
            name='secondary_email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='secondary_phone1',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='secondary_phone2',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
