# Generated by Django 3.0.3 on 2020-03-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='skype_id',
            new_name='skypeid',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='street_address',
            new_name='streetaddress',
        ),
    ]
