# Generated by Django 3.0.3 on 2020-04-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignto',
            old_name='assign_tos',
            new_name='assign_to',
        ),
    ]
