# Generated by Django 3.0.3 on 2020-03-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200320_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='values',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='valuesphone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
