# Generated by Django 3.0.3 on 2020-02-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accounts_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
