# Generated by Django 3.0.3 on 2020-03-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200303_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
