# Generated by Django 3.0.3 on 2020-03-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200304_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
